### ISSUE TITLE
[Question] Comparision to linc_luajit

### ISSUE THREAD

**Issue by TheDrawingCoder-Gamer** [kevinresol/hxvm-lua#4]
I'm considering switching my project from [linc_luajit](https://github.com/AndreiRudenko/linc_luajit) to hxvm-lua.  Are there caveats/known issues with hxvm-lua? It seems it's high level and this is like the JIT... and it also supports javascript. 

In short what are the benefits and drawbacks of making the switch?

**Comment by kevinresol** [comment]
Closing as no one really seem to have an answer after 2 years.
